Document: sigma
Title: Debian sigma Manual
Author: <insert document author here>
Abstract: This manual describes what sigma is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sigma/sigma.sgml.gz

Format: postscript
Files: /usr/share/doc/sigma/sigma.ps.gz

Format: text
Files: /usr/share/doc/sigma/sigma.text.gz

Format: HTML
Index: /usr/share/doc/sigma/html/index.html
Files: /usr/share/doc/sigma/html/*.html
